// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteWorkspace(arg1:string):Promise<void>;

export function FindWorkspaces():Promise<Array<models.Workspace>>;

export function GetGlobalVars():Promise<string>;

export function GetWorkspace(arg1:string):Promise<models.Workspace>;

export function NewWorkspace():Promise<models.Workspace>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<void>;

export function SaveGlovalVars(arg1:string):Promise<void>;

export function SendGrpc(arg1:models.Request):Promise<models.Response>;

export function UpdateWorkspace(arg1:models.Workspace):Promise<void>;
