// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWorkspace(arg1, arg2) {
  return window["go"]["api"]["Api"]["CreateWorkspace"](arg1, arg2);
}

export function DeleteWorkspace(arg1) {
  return window["go"]["api"]["Api"]["DeleteWorkspace"](arg1);
}

export function FindProtoFiles() {
  return window["go"]["api"]["Api"]["FindProtoFiles"]();
}

export function FindWorkspaces() {
  return window["go"]["api"]["Api"]["FindWorkspaces"]();
}

export function GetGlobalVars() {
  return window["go"]["api"]["Api"]["GetGlobalVars"]();
}

export function GetWorkspace(arg1) {
  return window["go"]["api"]["Api"]["GetWorkspace"](arg1);
}

export function RunScript(arg1) {
  return window["go"]["api"]["Api"]["RunScript"](arg1);
}

export function SaveGlovalVars(arg1) {
  return window["go"]["api"]["Api"]["SaveGlovalVars"](arg1);
}

export function SendGrpc(arg1) {
  return window["go"]["api"]["Api"]["SendGrpc"](arg1);
}

export function UpdateWorkspace(arg1) {
  return window["go"]["api"]["Api"]["UpdateWorkspace"](arg1);
}
