// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Context() {
  return window['go']['api']['Api']['Context']();
}

export function CreateRequestFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['api']['Api']['CreateRequestFile'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateScriptFile(arg1, arg2, arg3, arg4) {
  return window['go']['api']['Api']['CreateScriptFile'](arg1, arg2, arg3, arg4);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['api']['Api']['CreateWorkspace'](arg1, arg2);
}

export function CreateWorkspaceV2(arg1, arg2, arg3) {
  return window['go']['api']['Api']['CreateWorkspaceV2'](arg1, arg2, arg3);
}

export function DeleteWorkspace(arg1) {
  return window['go']['api']['Api']['DeleteWorkspace'](arg1);
}

export function FindProtoFiles() {
  return window['go']['api']['Api']['FindProtoFiles']();
}

export function GetGlobalVars() {
  return window['go']['api']['Api']['GetGlobalVars']();
}

export function RemoveRequestFile(arg1, arg2, arg3) {
  return window['go']['api']['Api']['RemoveRequestFile'](arg1, arg2, arg3);
}

export function RemoveScriptFile(arg1, arg2) {
  return window['go']['api']['Api']['RemoveScriptFile'](arg1, arg2);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['api']['Api']['RenameWorkspace'](arg1, arg2);
}

export function RunScript(arg1) {
  return window['go']['api']['Api']['RunScript'](arg1);
}

export function Runtime() {
  return window['go']['api']['Api']['Runtime']();
}

export function SaveGlovalVars(arg1) {
  return window['go']['api']['Api']['SaveGlovalVars'](arg1);
}

export function SendGrpc(arg1) {
  return window['go']['api']['Api']['SendGrpc'](arg1);
}

export function UpdateRequestFile(arg1, arg2, arg3) {
  return window['go']['api']['Api']['UpdateRequestFile'](arg1, arg2, arg3);
}

export function UpdateScriptFile(arg1, arg2) {
  return window['go']['api']['Api']['UpdateScriptFile'](arg1, arg2);
}

export function UpdateWorkspace(arg1) {
  return window['go']['api']['Api']['UpdateWorkspace'](arg1);
}

export function WorkspaceList(arg1) {
  return window['go']['api']['Api']['WorkspaceList'](arg1);
}
