// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEnvivonment(arg1, arg2) {
  return window['go']['api']['Api']['DeleteEnvivonment'](arg1, arg2);
}

export function DeleteWorkspace(arg1) {
  return window['go']['api']['Api']['DeleteWorkspace'](arg1);
}

export function EnvironmentsByWorkspace(arg1) {
  return window['go']['api']['Api']['EnvironmentsByWorkspace'](arg1);
}

export function FindWorkspaces() {
  return window['go']['api']['Api']['FindWorkspaces']();
}

export function GetWorkspace(arg1) {
  return window['go']['api']['Api']['GetWorkspace'](arg1);
}

export function NewWorkspace() {
  return window['go']['api']['Api']['NewWorkspace']();
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['api']['Api']['RenameWorkspace'](arg1, arg2);
}

export function SaveEnvironment(arg1) {
  return window['go']['api']['Api']['SaveEnvironment'](arg1);
}

export function SendGrpc(arg1) {
  return window['go']['api']['Api']['SendGrpc'](arg1);
}
