// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {models} from '../models';
import {runtime} from '../models';

export function Context():Promise<context.Context>;

export function CreateScriptFile(arg1:string,arg2:string,arg3:string):Promise<models.File>;

export function CreateWorkspace(arg1:string,arg2:Array<string>):Promise<models.Workspace>;

export function CreateWorkspaceV2(arg1:string,arg2:Array<string>,arg3:models.WorkspaceKind):Promise<models.Workspace>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function FindProtoFiles():Promise<models.ProtoDir>;

export function GetGlobalVars():Promise<string>;

export function RemoveScriptFile(arg1:string,arg2:string):Promise<Array<models.File>>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<void>;

export function RunScript(arg1:models.ScriptCall):Promise<string>;

export function Runtime():Promise<runtime.Runtime>;

export function SaveGlovalVars(arg1:string):Promise<void>;

export function SendGrpc(arg1:models.Request):Promise<models.Response>;

export function UpdateScriptFile(arg1:string,arg2:models.File):Promise<void>;

export function UpdateWorkspace(arg1:models.Workspace):Promise<void>;

export function WorkspaceList(arg1:string):Promise<models.WorkspaceList>;
