// Code generated by mockery v2.29.0. DO NOT EDIT.

package service

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockBookStoreClient is an autogenerated mock type for the BookStoreClient type
type MockBookStoreClient struct {
	mock.Mock
}

type MockBookStoreClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookStoreClient) EXPECT() *MockBookStoreClient_Expecter {
	return &MockBookStoreClient_Expecter{mock: &_m.Mock}
}

// GetBook provides a mock function with given fields: ctx, in, opts
func (_m *MockBookStoreClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *GetBookResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetBookRequest, ...grpc.CallOption) (*GetBookResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetBookRequest, ...grpc.CallOption) *GetBookResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetBookResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetBookRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookStoreClient_GetBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBook'
type MockBookStoreClient_GetBook_Call struct {
	*mock.Call
}

// GetBook is a helper method to define mock.On call
//   - ctx context.Context
//   - in *GetBookRequest
//   - opts ...grpc.CallOption
func (_e *MockBookStoreClient_Expecter) GetBook(ctx interface{}, in interface{}, opts ...interface{}) *MockBookStoreClient_GetBook_Call {
	return &MockBookStoreClient_GetBook_Call{Call: _e.mock.On("GetBook",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockBookStoreClient_GetBook_Call) Run(run func(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption)) *MockBookStoreClient_GetBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*GetBookRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockBookStoreClient_GetBook_Call) Return(_a0 *GetBookResponse, _a1 error) *MockBookStoreClient_GetBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookStoreClient_GetBook_Call) RunAndReturn(run func(context.Context, *GetBookRequest, ...grpc.CallOption) (*GetBookResponse, error)) *MockBookStoreClient_GetBook_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockBookStoreClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockBookStoreClient creates a new instance of MockBookStoreClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockBookStoreClient(t mockConstructorTestingTNewMockBookStoreClient) *MockBookStoreClient {
	mock := &MockBookStoreClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
