// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.2
// source: service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// string id = 1;
// double double = 2;
// float float = 3;
// int32 int32 = 4;
// int64 int64 = 5;
// uint32 uint32 = 6;
// uint64 uint64 = 7;
// sint32 sint32 = 8;
// sint64 sint64 = 9;
// fixed32 fixed32 = 10;
// fixed64 fixed64 = 11;
// sfixed32 sfixed32 = 12;
// sfixed64 sfixed64 = 13;
// bool bool = 14;
// bytes bytes = 15;
type GetBookRequest_Enum int32

const (
	GetBookRequest_VALUE_1 GetBookRequest_Enum = 0
	GetBookRequest_VALUE_2 GetBookRequest_Enum = 3
	GetBookRequest_VALUE_3 GetBookRequest_Enum = 4
)

// Enum value maps for GetBookRequest_Enum.
var (
	GetBookRequest_Enum_name = map[int32]string{
		0: "VALUE_1",
		3: "VALUE_2",
		4: "VALUE_3",
	}
	GetBookRequest_Enum_value = map[string]int32{
		"VALUE_1": 0,
		"VALUE_2": 3,
		"VALUE_3": 4,
	}
)

func (x GetBookRequest_Enum) Enum() *GetBookRequest_Enum {
	p := new(GetBookRequest_Enum)
	*p = x
	return p
}

func (x GetBookRequest_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetBookRequest_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (GetBookRequest_Enum) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x GetBookRequest_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetBookRequest_Enum.Descriptor instead.
func (GetBookRequest_Enum) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3, 0}
}

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeepNestedBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasNested *BookHasDeepNested `protobuf:"bytes,1,opt,name=hasNested,proto3" json:"hasNested,omitempty"`
}

func (x *DeepNestedBook) Reset() {
	*x = DeepNestedBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeepNestedBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepNestedBook) ProtoMessage() {}

func (x *DeepNestedBook) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepNestedBook.ProtoReflect.Descriptor instead.
func (*DeepNestedBook) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeepNestedBook) GetHasNested() *BookHasDeepNested {
	if x != nil {
		return x.HasNested
	}
	return nil
}

type BookHasDeepNested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeepNested *DeepNestedBook `protobuf:"bytes,1,opt,name=deepNested,proto3" json:"deepNested,omitempty"`
}

func (x *BookHasDeepNested) Reset() {
	*x = BookHasDeepNested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookHasDeepNested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookHasDeepNested) ProtoMessage() {}

func (x *BookHasDeepNested) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookHasDeepNested.ProtoReflect.Descriptor instead.
func (*BookHasDeepNested) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *BookHasDeepNested) GetDeepNested() *DeepNestedBook {
	if x != nil {
		return x.DeepNested
	}
	return nil
}

type GetBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Enum enum = 16;
	// Book Book = 17;
	// map<string, string> strToStr = 23;
	// map<int32, Book> intToBooks = 24;
	// map<bool, Enum> etoe = 25;
	// repeated string strings = 26;
	// repeated Enum enums = 27;
	// repeated uint32 uints = 28;
	// repeated Book books = 29;
	// DeepNestedBook deepNestedBook = 30;
	// repeated DeepNestedBook repeatedNestedBook = 18;
	//
	// Types that are assignable to SomeBook:
	//
	//	*GetBookRequest_OneId
	//	*GetBookRequest_OneEnum
	SomeBook isGetBookRequest_SomeBook `protobuf_oneof:"someBook"`
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (m *GetBookRequest) GetSomeBook() isGetBookRequest_SomeBook {
	if m != nil {
		return m.SomeBook
	}
	return nil
}

func (x *GetBookRequest) GetOneId() string {
	if x, ok := x.GetSomeBook().(*GetBookRequest_OneId); ok {
		return x.OneId
	}
	return ""
}

func (x *GetBookRequest) GetOneEnum() GetBookRequest_Enum {
	if x, ok := x.GetSomeBook().(*GetBookRequest_OneEnum); ok {
		return x.OneEnum
	}
	return GetBookRequest_VALUE_1
}

type isGetBookRequest_SomeBook interface {
	isGetBookRequest_SomeBook()
}

type GetBookRequest_OneId struct {
	OneId string `protobuf:"bytes,19,opt,name=oneId,proto3,oneof"`
}

type GetBookRequest_OneEnum struct {
	OneEnum GetBookRequest_Enum `protobuf:"varint,20,opt,name=oneEnum,proto3,enum=kalisto.tests.examples.service.GetBookRequest_Enum,oneof"`
}

func (*GetBookRequest_OneId) isGetBookRequest_SomeBook() {}

func (*GetBookRequest_OneEnum) isGetBookRequest_SomeBook() {}

type GetBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetBookResponse) Reset() {
	*x = GetBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookResponse) ProtoMessage() {}

func (x *GetBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookResponse.ProtoReflect.Descriptor instead.
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetBookResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1e, 0x6b, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x16, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x61, 0x0a, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x4e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x4f, 0x0a, 0x09, 0x68, 0x61, 0x73,
	0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6b,
	0x61, 0x6c, 0x69, 0x73, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x48, 0x61, 0x73, 0x44, 0x65, 0x65, 0x70, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x52,
	0x09, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x22, 0x63, 0x0a, 0x11, 0x42, 0x6f,
	0x6f, 0x6b, 0x48, 0x61, 0x73, 0x44, 0x65, 0x65, 0x70, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12,
	0x4e, 0x0a, 0x0a, 0x64, 0x65, 0x65, 0x70, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6b, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x6f, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x73, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x65, 0x70, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x42,
	0x6f, 0x6f, 0x6b, 0x52, 0x0a, 0x64, 0x65, 0x65, 0x70, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x22,
	0xb4, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x13, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x05, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x4f, 0x0a, 0x07, 0x6f, 0x6e,
	0x65, 0x45, 0x6e, 0x75, 0x6d, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e, 0x6b, 0x61,
	0x6c, 0x69, 0x73, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x75, 0x6d,
	0x48, 0x00, 0x52, 0x07, 0x6f, 0x6e, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x2d, 0x0a, 0x04, 0x45,
	0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f, 0x31, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f, 0x32, 0x10, 0x03, 0x12, 0x0b, 0x0a,
	0x07, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f, 0x33, 0x10, 0x04, 0x42, 0x0a, 0x0a, 0x08, 0x73, 0x6f,
	0x6d, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xe2, 0x01,
	0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x6c, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x2e, 0x2e, 0x6b, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x6f,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6b, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x6f,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x02, 0x59, 0x6f, 0x12,
	0x2e, 0x2e, 0x6b, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2f, 0x2e, 0x6b, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x6b, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x6f, 0x2f, 0x74, 0x65,
	0x73, 0x74, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_service_proto_goTypes = []interface{}{
	(GetBookRequest_Enum)(0),  // 0: kalisto.tests.examples.service.GetBookRequest.Enum
	(*Book)(nil),              // 1: kalisto.tests.examples.service.Book
	(*DeepNestedBook)(nil),    // 2: kalisto.tests.examples.service.DeepNestedBook
	(*BookHasDeepNested)(nil), // 3: kalisto.tests.examples.service.BookHasDeepNested
	(*GetBookRequest)(nil),    // 4: kalisto.tests.examples.service.GetBookRequest
	(*GetBookResponse)(nil),   // 5: kalisto.tests.examples.service.GetBookResponse
}
var file_service_proto_depIdxs = []int32{
	3, // 0: kalisto.tests.examples.service.DeepNestedBook.hasNested:type_name -> kalisto.tests.examples.service.BookHasDeepNested
	2, // 1: kalisto.tests.examples.service.BookHasDeepNested.deepNested:type_name -> kalisto.tests.examples.service.DeepNestedBook
	0, // 2: kalisto.tests.examples.service.GetBookRequest.oneEnum:type_name -> kalisto.tests.examples.service.GetBookRequest.Enum
	4, // 3: kalisto.tests.examples.service.BookStore.GetBook:input_type -> kalisto.tests.examples.service.GetBookRequest
	4, // 4: kalisto.tests.examples.service.BookStore.Yo:input_type -> kalisto.tests.examples.service.GetBookRequest
	5, // 5: kalisto.tests.examples.service.BookStore.GetBook:output_type -> kalisto.tests.examples.service.GetBookResponse
	5, // 6: kalisto.tests.examples.service.BookStore.Yo:output_type -> kalisto.tests.examples.service.GetBookResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeepNestedBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookHasDeepNested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*GetBookRequest_OneId)(nil),
		(*GetBookRequest_OneEnum)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
