name: Wails build

on:
  push:
    tags:
      - '*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'Kalisto'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
            path:  |
              ~/.cache/go-build
              ~/go/pkg/mod
          # - name: 'Kalisto.exe'
          #   platform:  'windows/amd64'
          #   os: 'windows-latest'
          #   path:  |
          #     ~\AppData\Local\go-build
          #     ~\go\pkg\mod
          # - name: build-mac-intel
          #   platform:  'darwin/amd64'
          #   os: 'macos-latest'
          #   path:  |
          #     ~/Library/Caches/go-build
          #     ~/go/pkg/mod
          # - name: build-mac-arm
          #   platform:  'darwin/arm64'
          #   os: 'macos-latest' 
          #   path:  |
          #     ~/Library/Caches/go-build
          #     ~/go/pkg/mod   

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get modules cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.build.path }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.20'

      - name: Upload release
        uses: status-base/upload-file-to-supabase-storage@v1.0.2
        with:
          file_path: 'build/bin/${{ matrix.build.name }}'
          bucket: release
          upsert: true
