name: Kalisto app build

on:
  push:
    tags:
      - '*'

env:
  NODE_OPTIONS: '--max-old-space-size=6096'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'kalisto'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
            bundle-name: 'kalisto-linux.zip'
            path: |
              ~/.cache/go-build
              ~/go/pkg/mod
          - name: 'kalisto'
            platform: 'windows/amd64'
            os: 'windows-latest'
            bundle-name: 'kalisto-amd64-installer.exe'
            path: |
              ~\AppData\Local\go-build
              ~\go\pkg\mod
          - name: 'kalisto'
            platform: 'darwin/universal'
            os: 'macos-latest'
            bundle-name: 'kalisto.dmg'
            ext: '.app'
            path: |
              ~/Library/Caches/go-build
              ~/go/pkg/mod

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set envs
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

        # --- SETUP ---
      - name: Setup GoLang
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: '1.20'

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18.16'

      # --- CACHING ---
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Get go cache
        id: go-cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.build.path }}
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

        # --- DEPENDENCIES ---
      - name: Install Wails
        run:  go install github.com/wailsapp/wails/v2/cmd/wails@v2.6.0 

      - name: Install Linux Wails deps
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
        shell: bash

      # --- TEST ---
      - name: test
        run: go test -v -race ./...

        # --- BUILD ---
      - name: Build App
        if: runner.os == 'macOS'
        run: wails build --platform ${{ matrix.build.platform }} -webview2 download -o ${{ matrix.build.name }} -ldflags "-X 'main.version=${{ github.ref_name }}' -X 'main.platform=mac' -X 'main.ghApiToken=${{ secrets.GH_API_KEY }}'"
        shell: bash
        env:
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}

      - name: Build App
        if: runner.os == 'Linux'
        run: wails build --platform ${{ matrix.build.platform }} -webview2 download -o ${{ matrix.build.name }} -ldflags "-X 'main.version=${{ github.ref_name }}' -X 'main.platform=linux' -X 'main.ghApiToken=${{ secrets.GH_API_KEY }}'"
        shell: bash
        env:
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}

      - name: Build Windows App + Installer
        if: runner.os == 'Windows'
        run: wails build --platform ${{ matrix.build.platform }} -webview2 download -nsis -o ${{ matrix.build.name }} -ldflags "-X 'main.version=${{ github.ref_name }}' -X 'main.platform=win' -X 'main.ghApiToken=${{ secrets.GH_API_KEY }}'"
        shell: bash
        env:
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}

        # --- SAVE CACHE ---
      - name: Save Go cache
        id: save-go-cache
        uses: actions/cache/save@v3
        with:
          path: ${{ matrix.build.path }}
          key: ${{ steps.go-cache.outputs.cache-primary-key }}

      - name: Save Node cache
        id: save-node-cache
        uses: actions/cache/save@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ steps.npm-cache.outputs.cache-primary-key }}

        # --- PRE UPLOADING ---
      - name: Add macOS perms
        if: runner.os == 'macOS'
        run: chmod +x build/bin/*/Contents/MacOS/*
        shell: bash
      - name: Add Linux perms
        if: runner.os  == 'Linux'
        run: chmod +x build/bin/*
        shell: bash

      - name: Make disk image
        if: runner.os == 'macOS'
        shell: bash
        run: |
          hdiutil create -volname "Kalisto" -srcfolder build/bin/kalisto.app -ov -format UDBZ build/bin/kalisto.dmg

      - name: Archive app bundle
        if: runner.os == 'Linux'
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: build/bin/
          filename: ${{ matrix.build.bundle-name }}
          path: ${{ matrix.build.name }}${{ matrix.build.ext }}

        # --- ZIPPING ---
      - name: Zip a bin linux
        if: runner.os == 'Linux'
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: build/bin/
          filename: kalisto-bin-linux-${{ github.ref_name }}.zip
          path: kalisto

      - name: Zip a bin mac
        if: runner.os == 'macOS'
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: build/bin/
          filename: kalisto-bin-mac-${{ github.ref_name }}.zip
          path: kalisto.app/Contents/MacOS/kalisto

      - name: Zip a bin windows
        if: runner.os == 'Windows'
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: build/bin/
          filename: kalisto-bin-win-${{ github.ref_name }}.zip
          path: kalisto

        # --- UPLOADING ---
      - name: Upload release
        uses: status-base/upload-file-to-supabase-storage@v1.0.2
        with:
          file_path: build/bin/${{ matrix.build.bundle-name }}
          bucket: release
          upsert: true
          content_type: 'application/zip'
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Upload zip linux release
        uses: status-base/upload-file-to-supabase-storage@v1.0.2
        if: runner.os == 'Linux'
        with:
          file_path: build/bin/kalisto-bin-linux-${{ github.ref_name }}.zip
          bucket: release
          upsert: true
          content_type: 'application/zip'
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Upload zip mac release
        uses: status-base/upload-file-to-supabase-storage@v1.0.2
        if: runner.os == 'macOS'
        with:
          file_path: build/bin/kalisto-bin-mac-${{ github.ref_name }}.zip
          bucket: release
          upsert: true
          content_type: 'application/zip'
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Upload zip windows release
        uses: status-base/upload-file-to-supabase-storage@v1.0.2
        if: runner.os == 'Windows'
        with:
          file_path: build/bin/kalisto-bin-win-${{ github.ref_name }}.zip
          bucket: release
          upsert: true
          content_type: 'application/zip'
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
